steps:
  - name: "node"
    entrypoint: "npm"
    args:
      - install
  - name: "node"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        curl -LJO https://github.com/gohugoio/hugo/releases/download/v0.117.0/hugo_0.117.0_linux-amd64.deb
        dpkg -i hugo_0.117.0_linux-amd64.deb
        which hugo
        npm run build
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', '/workspace/public/', 'gs://tina2.phunh.com/']