steps:
  - name: "node"
    entrypoint: "npm"
    args:
      - install
  - name: "node"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        brew install hugo
        npm run build